spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

comment.avatar: /images/avatar.jpg